"""
Advanced Retrieval — Step-back prompting and self-ask.

Implements advanced retrieval strategies for better answer quality.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import httpx

logger = logging.getLogger(__name__)

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"


class RetrievalStrategy(str, Enum):
    STANDARD = "standard"
    STEP_BACK = "step_back"
    SELF_ASK = "self_ask"
    MULTI_QUERY = "multi_query"


@dataclass
class AdvancedRetrievalConfig:
    """Configuration for advanced retrieval."""
    strategy: RetrievalStrategy = RetrievalStrategy.STANDARD
    max_sub_questions: int = 3
    max_step_back_levels: int = 2
    confidence_threshold: float = 0.7


@dataclass
class SubQuestion:
    """A sub-question generated by self-ask."""
    question: str
    answer: Optional[str] = None
    source: Optional[str] = None


@dataclass
class StepBackQuery:
    """A step-back query."""
    original_query: str
    step_back_query: str
    level: int
    reasoning: str


@dataclass
class AdvancedRetrievalResult:
    """Result of advanced retrieval."""
    strategy_used: RetrievalStrategy
    original_query: str
    expanded_queries: list[str] = field(default_factory=list)
    sub_questions: list[SubQuestion] = field(default_factory=list)
    step_back_queries: list[StepBackQuery] = field(default_factory=list)
    context: str = ""
    confidence: float = 0.0


# System prompts
STEP_BACK_PROMPT = """You are an AI assistant that helps with step-back reasoning.

Given a specific question, generate a more general, foundational question that would help answer the original question.

Rules:
1. The step-back question should be broader and more general
2. It should capture background knowledge needed
3. Keep it concise and clear

Specific question: {query}

Generate a step-back question:"""


SELF_ASK_PROMPT = """You are an AI assistant that breaks down complex questions.

Given a question, break it down into simpler sub-questions that can be answered independently.

Rules:
1. Generate up to {max_questions} sub-questions
2. Each sub-question should be answerable on its own
3. Together, they should help answer the original question
4. Order from most fundamental to most specific

Complex question: {query}

Generate sub-questions (JSON format):
{{
  "sub_questions": ["<question1>", "<question2>", ...]
}}"""


MULTI_QUERY_PROMPT = """You are an AI query optimizer.

Given a query, generate multiple alternative queries that capture different aspects of the information need.

Rules:
1. Generate {num_variants} alternative queries
2. Each should approach the topic differently
3. Use synonyms and different phrasings

Original query: {query}

Generate alternative queries (JSON format):
{{
  "queries": ["<query1>", "<query2>", ...]
}}"""


class AdvancedRetrieval:
    """Advanced retrieval service."""

    def __init__(self, config: Optional[AdvancedRetrievalConfig] = None):
        self.config = config or AdvancedRetrievalConfig()

    async def step_back(
        self,
        query: str,
        api_key: str,
        model: str,
        level: int = 1,
    ) -> StepBackQuery:
        """
        Generate a step-back query.

        Args:
            query: Original query
            api_key: LLM API key
            model: LLM model
            level: Step-back level (1 = one step back)

        Returns:
            StepBackQuery with the broader question
        """
        try:
            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost:3000",
                "X-Title": "ContextOS Step-Back",
            }

            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": "You are a step-back reasoning assistant."},
                    {
                        "role": "user",
                        "content": STEP_BACK_PROMPT.format(query=query),
                    },
                ],
                "temperature": 0.3,
                "max_tokens": 200,
            }

            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(OPENROUTER_URL, headers=headers, json=payload)

                if response.status_code != 200:
                    return StepBackQuery(
                        original_query=query,
                        step_back_query=query,
                        level=level,
                        reasoning="Step-back generation failed",
                    )

                result = response.json()
                step_back_query = result["choices"][0]["message"]["content"].strip()

                return StepBackQuery(
                    original_query=query,
                    step_back_query=step_back_query,
                    level=level,
                    reasoning=f"Step-back level {level}",
                )

        except Exception as e:
            logger.warning(f"Step-back generation error: {e}")
            return StepBackQuery(
                original_query=query,
                step_back_query=query,
                level=level,
                reasoning=f"Error: {e}",
            )

    async def self_ask(
        self,
        query: str,
        api_key: str,
        model: str,
    ) -> list[SubQuestion]:
        """
        Break down a complex question into sub-questions.

        Args:
            query: Complex question
            api_key: LLM API key
            model: LLM model

        Returns:
            List of SubQuestion
        """
        try:
            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost:3000",
                "X-Title": "ContextOS Self-Ask",
            }

            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": "You are a question decomposition assistant."},
                    {
                        "role": "user",
                        "content": SELF_ASK_PROMPT.format(
                            query=query,
                            max_questions=self.config.max_sub_questions,
                        ),
                    },
                ],
                "temperature": 0.3,
                "max_tokens": 500,
            }

            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(OPENROUTER_URL, headers=headers, json=payload)

                if response.status_code != 200:
                    return [SubQuestion(question=query)]

                result = response.json()
                content = result["choices"][0]["message"]["content"]

                # Parse JSON
                if "```json" in content:
                    content = content.split("```json")[1].split("```")[0]
                elif "```" in content:
                    content = content.split("```")[1].split("```")[0]

                data = json.loads(content)
                sub_questions = data.get("sub_questions", [query])

                return [SubQuestion(question=q) for q in sub_questions[:self.config.max_sub_questions]]

        except Exception as e:
            logger.warning(f"Self-ask generation error: {e}")
            return [SubQuestion(question=query)]

    async def multi_query(
        self,
        query: str,
        api_key: str,
        model: str,
        num_variants: int = 3,
    ) -> list[str]:
        """
        Generate multiple query variants.

        Args:
            query: Original query
            api_key: LLM API key
            model: LLM model
            num_variants: Number of variants to generate

        Returns:
            List of query variants
        """
        try:
            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost:3000",
                "X-Title": "ContextOS Multi-Query",
            }

            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": "You are a query optimizer."},
                    {
                        "role": "user",
                        "content": MULTI_QUERY_PROMPT.format(
                            query=query,
                            num_variants=num_variants,
                        ),
                    },
                ],
                "temperature": 0.5,
                "max_tokens": 300,
            }

            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(OPENROUTER_URL, headers=headers, json=payload)

                if response.status_code != 200:
                    return [query]

                result = response.json()
                content = result["choices"][0]["message"]["content"]

                # Parse JSON
                if "```json" in content:
                    content = content.split("```json")[1].split("```")[0]
                elif "```" in content:
                    content = content.split("```")[1].split("```")[0]

                data = json.loads(content)
                queries = data.get("queries", [query])

                return queries[:num_variants]

        except Exception as e:
            logger.warning(f"Multi-query generation error: {e}")
            return [query]

    async def retrieve(
        self,
        query: str,
        search_fn,
        api_key: str,
        model: str,
    ) -> AdvancedRetrievalResult:
        """
        Execute advanced retrieval based on configured strategy.

        Args:
            query: User query
            search_fn: Async search function(query) -> results
            api_key: LLM API key
            model: LLM model

        Returns:
            AdvancedRetrievalResult
        """
        result = AdvancedRetrievalResult(
            strategy_used=self.config.strategy,
            original_query=query,
        )

        if self.config.strategy == RetrievalStrategy.STANDARD:
            # Simple search
            results = await search_fn(query)
            result.context = str(results)
            result.confidence = 0.8

        elif self.config.strategy == RetrievalStrategy.STEP_BACK:
            # Generate step-back queries
            step_backs = []
            current_query = query

            for level in range(1, self.config.max_step_back_levels + 1):
                step_back = await self.step_back(current_query, api_key, model, level)
                step_backs.append(step_back)
                current_query = step_back.step_back_query
                result.expanded_queries.append(step_back.step_back_query)

            result.step_back_queries = step_backs

            # Search with all queries
            all_results = []
            for q in [query] + [sb.step_back_query for sb in step_backs]:
                search_results = await search_fn(q)
                all_results.extend(search_results)

            result.context = str(all_results)
            result.confidence = 0.85

        elif self.config.strategy == RetrievalStrategy.SELF_ASK:
            # Break down into sub-questions
            sub_questions = await self.self_ask(query, api_key, model)

            # Answer each sub-question
            for sq in sub_questions:
                search_results = await search_fn(sq.question)
                sq.answer = str(search_results)
                sq.source = "search"
                result.sub_questions.append(sq)
                result.expanded_queries.append(sq.question)

            result.context = "\n".join(
                f"Q: {sq.question}\nA: {sq.answer}"
                for sq in sub_questions
            )
            result.confidence = 0.9

        elif self.config.strategy == RetrievalStrategy.MULTI_QUERY:
            # Generate multiple queries
            queries = await self.multi_query(query, api_key, model)
            result.expanded_queries = queries

            # Search with all queries
            all_results = []
            for q in queries:
                search_results = await search_fn(q)
                all_results.extend(search_results)

            result.context = str(all_results)
            result.confidence = 0.85

        return result
